package com.cubrid.common.ui.spi.event;

public enum CubridNodeChangedEventType {
	NODE_ADD, NODE_REMOVE, NODE_REFRESH, CONTAINER_NODE_REFRESH, SERVER_CONNECTED, SERVER_DISCONNECTED, DATABASE_LOGIN, DATABASE_LOGOUT, DATABASE_START, DATABASE_STOP
}
